### ISSUE TITLE
Update applicationKey/sharedSecret

### ISSUE THREAD

**Issue by gauffininteractive** [coderrapp/codeRR.Server#22]
Want to be able to update key and secret.

1. Old key must still work for a transition period
2. Should be able to revoke old key directly
3. The report receiver must accept all configured keys
4. All keys should be visible in the admin area
5. The newest key should be displayed in the application info (for all team members)

**Comment by jgauffin** [comment]
Will be implemented in codeRR Live instead. https://coderrapp.com/live/
