### ISSUE TITLE
about reopen status cannot update

### ISSUE THREAD

**Issue by kimx** [coderrapp/codeRR.Server#43]
After update 1.1, I have a Incidents which is closed, but if the same error occurred again the status will still be closed and not any report be generated.Is this act right?

**Comment by kimx** [comment]
By the way, yet another issue that notification email cannot be sent.

**Comment by jgauffin** [comment]
I have not been able to reproduce the errors that you describe.
However, try v1.1.01 and see if it works better.

Otherwise modify the `log4net.config` so that it logs property and then reproduce the error and finally attach the log to this issue

**Comment by kimx** [comment]
About v1.1.01, This time I try to use all new database but the problem still exists. As below are about issue and logs.
1.The incident status is closed then the same error occurred again the status is still closed not "Reopen" and not any new report.
Coderr.Errors.log
`2017-11-06 11:13:24,776 [62] ERROR codeRR.Server.ReportAnalyzer.Handlers.ProcessReportHandler [(null)] – Failed to analyze report 
System.ArgumentNullException: 值不能為 null。
參數名稱: principal
   於 DotNetCqs.Bus.SingleInstanceMessageBus.SendAsync(ClaimsPrincipal principal, Object message)
   於 codeRR.Server.ReportAnalyzer.Handlers.Reports.ReportAnalyzer.Analyze(ClaimsPrincipal user, ErrorReportEntity report)
   於 codeRR.Server.ReportAnalyzer.Handlers.ProcessReportHandler.HandleAsync(IMessageContext context, ProcessReport message)
`
2.Send mail fail.
Coderr.Errors.log same 1.
3.The solution field not being saved to the database.I watch the chrome developer tools and found the post data, not with the field.

**Comment by jgauffin** [comment]
I think that I have found it. Should have been corrected in the latest source code.
