### ISSUE TITLE
Dashboard why show all incidents

### ISSUE THREAD

**Issue by kimx** [coderrapp/codeRR.Server#47]
The dashboard default shows the wrong incidents which I expect its status is "New" but all of the incidents were showing. 
Below is the API URL and request payload is the dashboard was sent.
/api/cqs/?query=FindIncidents
`{SortType: 0, SortAscending: false, PageNumber: 1, ItemsPerPage: 10}
ItemsPerPage:10
PageNumber:1
SortAscending:false
SortType:0`
Obesouly ,that is lack the parameter  "IsNew:true"

**Comment by jgauffin** [comment]
Corrected in the latest commit
