### ISSUE TITLE
configuring codeRR with WPF

### ISSUE THREAD

**Issue by mdziadowiec** [coderrapp/codeRR.Server#48]
Hi
Im trying to configure codeRR to work with WPF application. I have self hosted server and when im trying to add new app and select "Start the Configuration wizzard", then select WPF-based applications and press configure button all i get is page with: "Page not found, we could not find the page that you where looking for." How do i obtain app key and shered secret for WPF application?
There is no information link on the documentation page for WPF implementation codeRR.client.WPF (https://coderrapp.com/documentation/client/index.md)

**Comment by jgauffin** [comment]
Ok. I will update the documentation for WPF during this week.

In the mean time, click on any other library in the wizard to retrieve the appKey/SharedSecret.

Here is a configuration sample:
https://github.com/coderrapp/codeRR.Client.WPF/blob/master/src/Coderr.Client.Wpf.Demo/App.xaml.cs

**Comment by jgauffin** [comment]
*(the nuget package name is `coderr.client.wpf`)*

**Comment by mdziadowiec** [comment]
It works beautifull now, thanks for super quick response.
BTW any plans for UWP implementation?
