### ISSUE TITLE
E-mail account password not hidden

### ISSUE THREAD

**Issue by SamKr** [coderrapp/codeRR.Server#60]
Not a bug, just a small inconsistency. During installation, when entering the e-mail account password, the first box isn't hidden but the second one is:

![image](https://user-images.githubusercontent.com/1439763/37453256-70fef948-2837-11e8-9010-7d56c1ceb1ff.png)

**Comment by SamKr** [comment]
Update: this field is also readable in the /admin/messaging/email page, which makes it a bit more troublesome.

**Comment by jgauffin** [comment]
Corrected in the latest commit. thank you.
